/* Greek Vocabulary Writing Prompts — data module.
 * Exposes: VOCAB (word pool), SCENARIOS (prompt framings), THEMES (colour metadata).
 * The app (greekvocab.app.js) reads these as globals.
 *
 * Word schema:
 *   { gr, art, en, pos, theme, register, note? }
 *     gr       — the Greek word (with accents). Adjectives are given in the masculine.
 *     art      — definite article for nouns (ο/η/το), '' for non-nouns
 *     en       — English meaning / gloss
 *     pos      — 'noun' | 'adj' | 'adv' | 'verb'
 *     theme    — colour grouping (key of THEMES)
 *     register — 'everyday' (common, high-frequency) | 'expressive' (vivid/unusual)
 *     note     — optional context (shown on hover)
 *
 * The point of this section is a *blend*: everyday words that are hard to remember
 * sit next to expressive words that make writing feel alive. The mix slider in the UI
 * controls how many of each you get. Everyday words are deliberately common
 * (the kind you'd find on a frequency list); expressive words are chosen to be worth it.
 */

window.THEMES = {
  feeling:  { label: 'Feeling / mood',     color: '#ff9f43' },
  art:      { label: 'Art / aesthetic',    color: '#b78cff' },
  mind:     { label: 'Mind / concept',     color: '#7fdcff' },
  sense:    { label: 'Sense / sound',      color: '#8ee28e' },
  social:   { label: 'People / social',    color: '#ffd84d' },
  everyday: { label: 'Everyday',           color: '#9aa6b2' }
};

window.VOCAB = [
  /* =========================================================
   *  EVERYDAY — common, high-frequency words (the hard-to-stick ones)
   * ========================================================= */
  // Home & objects
  { gr: 'τραπέζι',     art: 'το', en: 'table',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'καρέκλα',     art: 'η',  en: 'chair',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'κρεβάτι',     art: 'το', en: 'bed',                pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'πόρτα',       art: 'η',  en: 'door',               pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'παράθυρο',    art: 'το', en: 'window',             pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'κουρτίνα',    art: 'η',  en: 'curtain',            pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'ντουλάπι',    art: 'το', en: 'cupboard, cabinet',  pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'ντουλάπα',    art: 'η',  en: 'wardrobe',           pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'ψυγείο',      art: 'το', en: 'fridge',             pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'κουζίνα',     art: 'η',  en: 'kitchen, cooker',    pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'καναπές',     art: 'ο',  en: 'sofa',               pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'χαλί',        art: 'το', en: 'rug, carpet',        pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'τοίχος',      art: 'ο',  en: 'wall',               pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'πάτωμα',      art: 'το', en: 'floor',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'σκάλα',       art: 'η',  en: 'stairs, ladder',     pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'κλειδί',      art: 'το', en: 'key',                pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'λάμπα',       art: 'η',  en: 'lamp',               pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'καθρέφτης',   art: 'ο',  en: 'mirror',             pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'πετσέτα',     art: 'η',  en: 'towel',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'σαπούνι',     art: 'το', en: 'soap',               pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'ρολόι',       art: 'το', en: 'clock, watch',       pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'πιάτο',       art: 'το', en: 'plate',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'ποτήρι',      art: 'το', en: 'glass',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'κουτάλι',     art: 'το', en: 'spoon',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'πιρούνι',     art: 'το', en: 'fork',               pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'μαχαίρι',     art: 'το', en: 'knife',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  // Food & drink
  { gr: 'ψωμί',        art: 'το', en: 'bread',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'νερό',        art: 'το', en: 'water',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'γάλα',        art: 'το', en: 'milk',               pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'καφές',       art: 'ο',  en: 'coffee',             pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'τυρί',        art: 'το', en: 'cheese',             pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'αυγό',        art: 'το', en: 'egg',                pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'ζάχαρη',      art: 'η',  en: 'sugar',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'αλάτι',       art: 'το', en: 'salt',               pos: 'noun', theme: 'everyday', register: 'everyday' },
  // People, body, daily life
  { gr: 'χέρι',        art: 'το', en: 'hand, arm',          pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'πόδι',        art: 'το', en: 'leg, foot',          pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'κεφάλι',      art: 'το', en: 'head',               pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'μάτι',        art: 'το', en: 'eye',                pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'καρδιά',      art: 'η',  en: 'heart',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'φίλος',       art: 'ο',  en: 'friend',             pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'οικογένεια',  art: 'η',  en: 'family',             pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'παιδί',       art: 'το', en: 'child',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'δουλειά',     art: 'η',  en: 'work, job',          pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'σπίτι',       art: 'το', en: 'house, home',        pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'αυτοκίνητο',  art: 'το', en: 'car',                pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'δρόμος',      art: 'ο',  en: 'road, street',       pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'μαγαζί',      art: 'το', en: 'shop',               pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'λεφτά',       art: 'τα', en: 'money',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'καιρός',      art: 'ο',  en: 'weather, time',      pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'εβδομάδα',    art: 'η',  en: 'week',               pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'πρωί',        art: 'το', en: 'morning',            pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'βράδυ',       art: 'το', en: 'evening',            pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'κοινότητα',   art: 'η',  en: 'community',          pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'υποχρέωση',   art: 'η',  en: 'obligation, commitment', pos: 'noun', theme: 'everyday', register: 'everyday', note: 'Obligation / commitment. (Everyday "routine" is usually ρουτίνα.)' },
  // Clothing
  { gr: 'παντελόνι',   art: 'το', en: 'trousers',           pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'πουκάμισο',   art: 'το', en: 'shirt',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'φόρεμα',      art: 'το', en: 'dress',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'παπούτσι',    art: 'το', en: 'shoe',               pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'τσάντα',      art: 'η',  en: 'bag',                pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'μπουφάν',     art: 'το', en: 'jacket',             pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'κάλτσα',      art: 'η',  en: 'sock',               pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'καπέλο',      art: 'το', en: 'hat',                pos: 'noun', theme: 'everyday', register: 'everyday' },
  // City & transport
  { gr: 'λεωφορείο',   art: 'το', en: 'bus',                pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'τρένο',       art: 'το', en: 'train',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'αεροπλάνο',   art: 'το', en: 'aeroplane',          pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'ποδήλατο',    art: 'το', en: 'bicycle',            pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'πλατεία',     art: 'η',  en: 'square (in a town)', pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'γειτονιά',    art: 'η',  en: 'neighbourhood',      pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'στάση',       art: 'η',  en: 'bus stop',           pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'εισιτήριο',   art: 'το', en: 'ticket',             pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'γέφυρα',      art: 'η',  en: 'bridge',             pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'κτίριο',      art: 'το', en: 'building',           pos: 'noun', theme: 'everyday', register: 'everyday' },
  // More home
  { gr: 'μπάνιο',      art: 'το', en: 'bathroom',           pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'φούρνος',     art: 'ο',  en: 'oven, bakery',       pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'πλυντήριο',   art: 'το', en: 'washing machine',    pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'σκούπα',      art: 'η',  en: 'broom',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'μαξιλάρι',    art: 'το', en: 'pillow, cushion',    pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'κουβέρτα',    art: 'η',  en: 'blanket',            pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'σεντόνι',     art: 'το', en: 'bed sheet',          pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'ράφι',        art: 'το', en: 'shelf',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'συρτάρι',     art: 'το', en: 'drawer',             pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'πρίζα',       art: 'η',  en: 'plug socket',        pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'διακόπτης',   art: 'ο',  en: 'light switch',       pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'κάδος',       art: 'ο',  en: 'bin',                pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'καλοριφέρ',   art: 'το', en: 'radiator',           pos: 'noun', theme: 'everyday', register: 'everyday' },
  // More kitchen & food
  { gr: 'φλιτζάνι',    art: 'το', en: 'cup',                pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'κατσαρόλα',   art: 'η',  en: 'cooking pot',        pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'τηγάνι',      art: 'το', en: 'frying pan',         pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'μπουκάλι',    art: 'το', en: 'bottle',             pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'κρέας',       art: 'το', en: 'meat',               pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'ψάρι',        art: 'το', en: 'fish',               pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'λάδι',        art: 'το', en: 'oil',                pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'ντομάτα',     art: 'η',  en: 'tomato',             pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'πατάτα',      art: 'η',  en: 'potato',             pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'μήλο',        art: 'το', en: 'apple',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'κρασί',       art: 'το', en: 'wine',               pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'μπύρα',       art: 'η',  en: 'beer',               pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'τσάι',        art: 'το', en: 'tea',                pos: 'noun', theme: 'everyday', register: 'everyday' },
  // Tech & desk
  { gr: 'υπολογιστής', art: 'ο',  en: 'computer',           pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'κινητό',      art: 'το', en: 'mobile phone',       pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'οθόνη',       art: 'η',  en: 'screen',             pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'γραφείο',     art: 'το', en: 'desk, office',       pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'χαρτί',       art: 'το', en: 'paper',              pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'στυλό',       art: 'το', en: 'pen',                pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'μολύβι',      art: 'το', en: 'pencil',             pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'βιβλίο',      art: 'το', en: 'book',               pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'εφημερίδα',   art: 'η',  en: 'newspaper',          pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'γυαλιά',      art: 'τα', en: 'glasses',            pos: 'noun', theme: 'everyday', register: 'everyday' },
  { gr: 'ομπρέλα',     art: 'η',  en: 'umbrella',           pos: 'noun', theme: 'everyday', register: 'everyday' },
  // Common verbs
  { gr: 'μαντεύω',     art: '',   en: 'to guess',           pos: 'verb', theme: 'everyday', register: 'everyday' },
  { gr: 'περιγράφω',   art: '',   en: 'to describe',        pos: 'verb', theme: 'everyday', register: 'everyday' },
  { gr: 'καίω',        art: '',   en: 'to burn',            pos: 'verb', theme: 'everyday', register: 'everyday' },
  { gr: 'ξεχνάω',      art: '',   en: 'to forget',          pos: 'verb', theme: 'everyday', register: 'everyday' },
  { gr: 'ψάχνω',       art: '',   en: 'to look for, search',pos: 'verb', theme: 'everyday', register: 'everyday' },
  { gr: 'δοκιμάζω',    art: '',   en: 'to try, taste',      pos: 'verb', theme: 'everyday', register: 'everyday' },
  { gr: 'διαλέγω',     art: '',   en: 'to choose, pick',    pos: 'verb', theme: 'everyday', register: 'everyday' },
  { gr: 'κερδίζω',     art: '',   en: 'to win, earn',       pos: 'verb', theme: 'everyday', register: 'everyday' },
  // Common connectors / softeners (high-frequency, make speech natural)
  { gr: 'κάπως',       art: '',   en: 'kind of, somehow',   pos: 'adv',  theme: 'everyday', register: 'everyday', note: 'Tiny but very natural conversational softener.' },
  { gr: 'τελείως',     art: '',   en: 'completely, totally',pos: 'adv',  theme: 'everyday', register: 'everyday' },
  { gr: 'όντως',       art: '',   en: 'actually, genuinely',pos: 'adv',  theme: 'everyday', register: 'everyday', note: 'Makes speech feel natural very quickly.' },
  { gr: 'βασικά',      art: '',   en: 'basically',          pos: 'adv',  theme: 'everyday', register: 'everyday', note: 'Extremely common spoken connector.' },
  { gr: 'ακριβώς',     art: '',   en: 'exactly',            pos: 'adv',  theme: 'everyday', register: 'everyday' },
  { gr: 'ιδιαίτερα',   art: '',   en: 'particularly, especially', pos: 'adv', theme: 'everyday', register: 'everyday' },
  { gr: 'σχεδόν',      art: '',   en: 'almost',             pos: 'adv',  theme: 'everyday', register: 'everyday' },

  /* =========================================================
   *  EXPRESSIVE — vivid / unusual words worth the effort
   * ========================================================= */
  // --- Feeling / mood ---
  { gr: 'μελαγχολικός', art: '',  en: 'melancholic',        pos: 'adj',  theme: 'feeling', register: 'expressive', note: 'Soft, emotional, atmospheric. Useful for music, places, moods.' },
  { gr: 'νοσταλγικός',  art: '',  en: 'nostalgic',          pos: 'adj',  theme: 'feeling', register: 'expressive', note: 'Emotional memory: old gear, old places, old songs.' },
  { gr: 'εύθραυστος',   art: '',  en: 'fragile',            pos: 'adj',  theme: 'feeling', register: 'expressive', note: 'Emotional, aesthetic, delicate.' },
  { gr: 'παθιασμένος',  art: '',  en: 'passionate, obsessed',pos: 'adj', theme: 'feeling', register: 'expressive' },
  { gr: 'ανήσυχος',     art: '',  en: 'restless, uneasy',   pos: 'adj',  theme: 'feeling', register: 'expressive' },
  { gr: 'ήρεμος',       art: '',  en: 'calm, peaceful',     pos: 'adj',  theme: 'feeling', register: 'expressive' },
  { gr: 'μοναχικός',    art: '',  en: 'solitary, lonely',   pos: 'adj',  theme: 'feeling', register: 'expressive' },
  { gr: 'παρορμητικός', art: '',  en: 'impulsive',          pos: 'adj',  theme: 'feeling', register: 'expressive' },
  { gr: 'αμφίθυμος',    art: '',  en: 'ambivalent',         pos: 'adj',  theme: 'feeling', register: 'expressive' },
  { gr: 'αδιάφορος',    art: '',  en: 'indifferent',        pos: 'adj',  theme: 'feeling', register: 'expressive' },
  { gr: 'απαθής',       art: '',  en: 'apathetic',          pos: 'adj',  theme: 'feeling', register: 'expressive' },
  { gr: 'ψυχρός',       art: '',  en: 'cold (emotionally)', pos: 'adj',  theme: 'feeling', register: 'expressive' },
  { gr: 'νοσταλγία',    art: 'η', en: 'nostalgia',          pos: 'noun', theme: 'feeling', register: 'expressive' },
  { gr: 'λαχτάρα',      art: 'η', en: 'yearning, craving',  pos: 'noun', theme: 'feeling', register: 'expressive' },
  { gr: 'μελαγχολία',   art: 'η', en: 'melancholy',         pos: 'noun', theme: 'feeling', register: 'expressive' },
  { gr: 'γαλήνη',       art: 'η', en: 'serenity, calm',     pos: 'noun', theme: 'feeling', register: 'expressive' },
  { gr: 'δέος',         art: 'το',en: 'awe',                pos: 'noun', theme: 'feeling', register: 'expressive' },
  { gr: 'στοργή',       art: 'η', en: 'tender affection',   pos: 'noun', theme: 'feeling', register: 'expressive' },
  { gr: 'μεράκι',       art: 'το',en: 'doing something with soul/passion', pos: 'noun', theme: 'feeling', register: 'expressive' },
  { gr: 'καημός',       art: 'ο', en: 'heartache, deep longing', pos: 'noun', theme: 'feeling', register: 'expressive' },
  { gr: 'ευδαιμονία',   art: 'η', en: 'bliss, flourishing', pos: 'noun', theme: 'feeling', register: 'expressive' },
  { gr: 'αγωνία',       art: 'η', en: 'anguish, suspense',  pos: 'noun', theme: 'feeling', register: 'expressive' },
  { gr: 'θλίψη',        art: 'η', en: 'sorrow, grief',      pos: 'noun', theme: 'feeling', register: 'expressive' },
  { gr: 'έκσταση',      art: 'η', en: 'ecstasy, rapture',   pos: 'noun', theme: 'feeling', register: 'expressive' },
  { gr: 'διάθεση',      art: 'η', en: 'mood, disposition, vibe', pos: 'noun', theme: 'feeling', register: 'expressive' },
  { gr: 'συναίσθημα',   art: 'το',en: 'emotion, feeling',   pos: 'noun', theme: 'feeling', register: 'expressive' },
  { gr: 'ένταση',       art: 'η', en: 'intensity, tension', pos: 'noun', theme: 'feeling', register: 'expressive', note: 'Wonderful dual meaning.' },

  // --- Art / aesthetic ---
  { gr: 'ονειρικός',    art: '',  en: 'dreamlike, oneiric', pos: 'adj',  theme: 'art', register: 'expressive', note: 'Great for music, visuals, Athens at night.' },
  { gr: 'υπνωτικός',    art: '',  en: 'hypnotic',           pos: 'adj',  theme: 'art', register: 'expressive', note: 'Grooves, repetition, techno, granular stuff.' },
  { gr: 'ψυχεδελικός',  art: '',  en: 'psychedelic',        pos: 'adj',  theme: 'art', register: 'expressive', note: 'Expressive + genuinely useful.' },
  { gr: 'πειραματικός', art: '',  en: 'experimental',       pos: 'adj',  theme: 'art', register: 'expressive' },
  { gr: 'μινιμαλιστικός',art: '', en: 'minimalist',         pos: 'adj',  theme: 'art', register: 'expressive' },
  { gr: 'κινηματογραφικός',art:'',en: 'cinematic',          pos: 'adj',  theme: 'art', register: 'expressive' },
  { gr: 'οργανικός',    art: '',  en: 'organic',            pos: 'adj',  theme: 'art', register: 'expressive' },
  { gr: 'μηχανικός',    art: '',  en: 'mechanical',         pos: 'adj',  theme: 'art', register: 'expressive', note: 'Great contrast with οργανικός.' },
  { gr: 'αναλογικός',   art: '',  en: 'analog',             pos: 'adj',  theme: 'art', register: 'expressive', note: 'Synth-world essential.' },
  { gr: 'ποιητικός',    art: '',  en: 'poetic',             pos: 'adj',  theme: 'art', register: 'expressive' },
  { gr: 'εκφραστικός',  art: '',  en: 'expressive',         pos: 'adj',  theme: 'art', register: 'expressive' },
  { gr: 'ακατέργαστος', art: '',  en: 'raw, unrefined',     pos: 'adj',  theme: 'art', register: 'expressive' },
  { gr: 'τελετουργικός',art: '',  en: 'ritualistic',        pos: 'adj',  theme: 'art', register: 'expressive' },
  { gr: 'υπόγειος',     art: '',  en: 'underground, subterranean', pos: 'adj', theme: 'art', register: 'expressive', note: 'Music scenes, culture, atmosphere.' },
  { gr: 'πυκνός',       art: '',  en: 'dense',              pos: 'adj',  theme: 'art', register: 'expressive', note: 'Dense atmosphere, dense sound.' },
  { gr: 'ρυθμός',       art: 'ο', en: 'rhythm',             pos: 'noun', theme: 'art', register: 'expressive' },
  { gr: 'αρμονία',      art: 'η', en: 'harmony',            pos: 'noun', theme: 'art', register: 'expressive' },
  { gr: 'τόνος',        art: 'ο', en: 'tone, stress, emphasis', pos: 'noun', theme: 'art', register: 'expressive' },
  { gr: 'ροή',          art: 'η', en: 'flow',               pos: 'noun', theme: 'art', register: 'expressive' },
  { gr: 'ατμόσφαιρα',   art: 'η', en: 'atmosphere',         pos: 'noun', theme: 'art', register: 'expressive' },
  { gr: 'ξωτικό',       art: 'το',en: 'elf, sprite',        pos: 'noun', theme: 'art', register: 'expressive' },
  { gr: 'φάντασμα',     art: 'το',en: 'ghost',              pos: 'noun', theme: 'art', register: 'expressive' },
  { gr: 'καλειδοσκόπιο',art:'το', en: 'kaleidoscope',       pos: 'noun', theme: 'art', register: 'expressive' },

  // --- Mind / concept ---
  { gr: 'χαοτικός',     art: '',  en: 'chaotic',            pos: 'adj',  theme: 'mind', register: 'expressive' },
  { gr: 'αφηρημένος',   art: '',  en: 'abstract',           pos: 'adj',  theme: 'mind', register: 'expressive' },
  { gr: 'δυστοπικός',   art: '',  en: 'dystopian',          pos: 'adj',  theme: 'mind', register: 'expressive' },
  { gr: 'αυθεντικός',   art: '',  en: 'authentic',          pos: 'adj',  theme: 'mind', register: 'expressive' },
  { gr: 'επιφανειακός', art: '',  en: 'superficial',        pos: 'adj',  theme: 'mind', register: 'expressive' },
  { gr: 'βαθύς',        art: '',  en: 'deep',               pos: 'adj',  theme: 'mind', register: 'expressive' },
  { gr: 'υπαρξιακός',   art: '',  en: 'existential',        pos: 'adj',  theme: 'mind', register: 'expressive' },
  { gr: 'ρευστός',      art: '',  en: 'fluid',              pos: 'adj',  theme: 'mind', register: 'expressive' },
  { gr: 'μεταβατικός',  art: '',  en: 'transitional',       pos: 'adj',  theme: 'mind', register: 'expressive' },
  { gr: 'διαισθητικός', art: '',  en: 'intuitive',          pos: 'adj',  theme: 'mind', register: 'expressive' },
  { gr: 'ουδέτερος',    art: '',  en: 'neutral',            pos: 'adj',  theme: 'mind', register: 'expressive' },
  { gr: 'απόκοσμος',    art: '',  en: 'otherworldly, uncanny', pos: 'adj', theme: 'mind', register: 'expressive', note: 'Literally "from another world."' },
  { gr: 'αλλόκοτος',    art: '',  en: 'bizarre, uncanny',   pos: 'adj',  theme: 'mind', register: 'expressive', note: 'More textured than just "weird."' },
  { gr: 'νοοτροπία',    art: 'η', en: 'mindset, mentality', pos: 'noun', theme: 'mind', register: 'expressive' },
  { gr: 'συνείδηση',    art: 'η', en: 'consciousness',      pos: 'noun', theme: 'mind', register: 'expressive' },
  { gr: 'αντίληψη',     art: 'η', en: 'perception',         pos: 'noun', theme: 'mind', register: 'expressive' },
  { gr: 'πραγματικότητα',art:'η', en: 'reality',            pos: 'noun', theme: 'mind', register: 'expressive' },
  { gr: 'μεταμόρφωση',  art: 'η', en: 'transformation',     pos: 'noun', theme: 'mind', register: 'expressive' },
  { gr: 'προσωδία',     art: 'η', en: 'prosody',            pos: 'noun', theme: 'mind', register: 'expressive', note: 'Niche but philosophically perfect.' },
  { gr: 'γρίφος',       art: 'ο', en: 'riddle, enigma',     pos: 'noun', theme: 'mind', register: 'expressive' },
  { gr: 'παραίσθηση',   art: 'η', en: 'hallucination',      pos: 'noun', theme: 'mind', register: 'expressive' },

  // --- Sense / sound ---
  { gr: 'αιθέριος',     art: '',  en: 'ethereal',           pos: 'adj',  theme: 'sense', register: 'expressive', note: 'Perfect for ambient music, textures, pads.' },
  { gr: 'σκοτεινός',    art: '',  en: 'dark',               pos: 'adj',  theme: 'sense', register: 'expressive', note: 'Emotional/aesthetic darkness.' },
  { gr: 'θολός',        art: '',  en: 'blurry, hazy',       pos: 'adj',  theme: 'sense', register: 'expressive', note: 'Amazing metaphorical potential.' },
  { gr: 'ζωντανός',     art: '',  en: 'alive, vivid',       pos: 'adj',  theme: 'sense', register: 'expressive' },
  { gr: 'σιωπηλός',     art: '',  en: 'silent, quiet',      pos: 'adj',  theme: 'sense', register: 'expressive' },
  { gr: 'οξύς',         art: '',  en: 'sharp, acute',       pos: 'adj',  theme: 'sense', register: 'expressive', note: 'Sound, intellect, feeling, humour.' },
  { gr: 'αχνός',        art: '',  en: 'faint, hazy',        pos: 'adj',  theme: 'sense', register: 'expressive' },
  { gr: 'απέραντος',    art: '',  en: 'boundless, vast',    pos: 'adj',  theme: 'sense', register: 'expressive' },
  { gr: 'χροιά',        art: 'η', en: 'tone, timbre, colour of voice', pos: 'noun', theme: 'sense', register: 'expressive', note: 'Voice colour, sonic colour, emotional tone.' },
  { gr: 'ηχόχρωμα',     art: 'το',en: 'timbre (lit. "sound-colour")', pos: 'noun', theme: 'sense', register: 'expressive' },
  { gr: 'αίσθηση',      art: 'η', en: 'feeling, sensation, vibe', pos: 'noun', theme: 'sense', register: 'expressive', note: 'One of the richest, most flexible Greek words.' },
  { gr: 'φεγγάρι',      art: 'το',en: 'moon',               pos: 'noun', theme: 'sense', register: 'expressive' },
  { gr: 'αύρα',         art: 'η', en: 'breeze, aura',       pos: 'noun', theme: 'sense', register: 'expressive' },
  { gr: 'ομίχλη',       art: 'η', en: 'fog, mist',          pos: 'noun', theme: 'sense', register: 'expressive' },
  { gr: 'άρωμα',        art: 'το',en: 'fragrance, scent',   pos: 'noun', theme: 'sense', register: 'expressive' },
  { gr: 'ρίγος',        art: 'το',en: 'shiver, thrill',     pos: 'noun', theme: 'sense', register: 'expressive' },
  { gr: 'ανατριχίλα',   art: 'η', en: 'shudder, goosebumps',pos: 'noun', theme: 'sense', register: 'expressive' },
  { gr: 'σούρουπο',     art: 'το',en: 'dusk, nightfall',    pos: 'noun', theme: 'sense', register: 'expressive' },
  { gr: 'χάραμα',       art: 'το',en: 'daybreak, first light', pos: 'noun', theme: 'sense', register: 'expressive' },
  { gr: 'ψίθυρος',      art: 'ο', en: 'a whisper',          pos: 'noun', theme: 'sense', register: 'expressive' },
  { gr: 'σιωπή',        art: 'η', en: 'silence',            pos: 'noun', theme: 'sense', register: 'expressive' },
  { gr: 'ηχώ',          art: 'η', en: 'echo',               pos: 'noun', theme: 'sense', register: 'expressive' },
  { gr: 'σκιά',         art: 'η', en: 'shadow',             pos: 'noun', theme: 'sense', register: 'expressive' },
  { gr: 'λάμψη',        art: 'η', en: 'gleam, radiance',    pos: 'noun', theme: 'sense', register: 'expressive' },

  // --- People / social ---
  { gr: 'εσωστρεφής',   art: '',  en: 'introverted',        pos: 'adj',  theme: 'social', register: 'expressive' },
  { gr: 'εξωστρεφής',   art: '',  en: 'extroverted',        pos: 'adj',  theme: 'social', register: 'expressive' },
  { gr: 'περίεργος',    art: '',  en: 'curious / strange',  pos: 'adj',  theme: 'social', register: 'expressive', note: 'Means BOTH — very Greek-feeling concept.' },
  { gr: 'αυθόρμητος',   art: '',  en: 'spontaneous',        pos: 'adj',  theme: 'social', register: 'expressive' },
  { gr: 'ειλικρινής',   art: '',  en: 'sincere, honest',    pos: 'adj',  theme: 'social', register: 'expressive' },
  { gr: 'παράξενος',    art: '',  en: 'strange, odd',       pos: 'adj',  theme: 'social', register: 'expressive', note: 'A bit more everyday than αλλόκοτος.' },
  { gr: 'εκκεντρικός',  art: '',  en: 'eccentric',          pos: 'adj',  theme: 'social', register: 'expressive' },
  { gr: 'διακριτικός',  art: '',  en: 'subtle, discreet',   pos: 'adj',  theme: 'social', register: 'expressive' },
  { gr: 'αυστηρός',     art: '',  en: 'strict, severe',     pos: 'adj',  theme: 'social', register: 'expressive' },
  { gr: 'ανεπιτήδευτος',art: '',  en: 'unpretentious, unaffected', pos: 'adj', theme: 'social', register: 'expressive', note: 'Brilliant, nuanced Greek cultural word.' },
  { gr: 'αμέτοχος',     art: '',  en: 'uninvolved, detached',pos: 'adj', theme: 'social', register: 'expressive' },
  { gr: 'κυνικός',      art: '',  en: 'cynical',            pos: 'adj',  theme: 'social', register: 'expressive' },
  { gr: 'πονηρός',      art: '',  en: 'cunning, sly, mischievous', pos: 'adj', theme: 'social', register: 'expressive', note: 'Sly/crafty, but often playful — a knowing, mischievous streak.' },
  { gr: 'προφορά',      art: 'η', en: 'pronunciation, accent', pos: 'noun', theme: 'social', register: 'expressive' },
  { gr: 'παρουσία',     art: 'η', en: 'presence',           pos: 'noun', theme: 'social', register: 'expressive' },
  { gr: 'σύνδεση',      art: 'η', en: 'connection',         pos: 'noun', theme: 'social', register: 'expressive' },
  { gr: 'φασαρία',      art: 'η', en: 'commotion, fuss',    pos: 'noun', theme: 'social', register: 'expressive' },
  { gr: 'κουτσομπολιό', art: 'το',en: 'gossip',             pos: 'noun', theme: 'social', register: 'expressive' },
  { gr: 'φάρσα',        art: 'η', en: 'prank, farce',       pos: 'noun', theme: 'social', register: 'expressive' }
];

// Varied framings for the writing prompt. {n} is replaced with the word count.
window.SCENARIOS = [
  'Use all {n} words in a single, winding sentence.',
  'Write a short diary entry (3–4 sentences) about your day.',
  'Write the opening lines of a horror story.',
  'Describe a dream you had last night.',
  'Write a postcard to a friend from somewhere far away.',
  'Write a tiny love letter.',
  'Describe the scene outside your window right now.',
  'Write the opening of a fairy tale.',
  'Write a snippet of overheard dialogue between two strangers.',
  'Review an imaginary album using these words.',
  'Write a weather forecast for an imaginary place.',
  'Describe a memory from your childhood.',
  'Write a three-line poem.',
  'Write a confession.',
  'Write the back-cover blurb for a novel that does not exist.',
  'Describe a piece of music as if it were a place.',
  'Write a text message you would never actually send.',
  'Narrate one minute of an ordinary morning in slow motion.',
  // Adapted from flash-fiction / journaling prompt collections (Squibler, eadeverell)
  'Write a scene using ONLY dialogue.',
  'Retell something that happened to you this week, from a bystander’s point of view.',
  'Write about someone returning something they borrowed years ago.',
  'Write the scene right after a disaster, without ever saying what the disaster was.',
  'Write about a taxi that takes you where you NEED to go, not where you ask.',
  'Describe something completely ordinary as if you were seeing it for the first time.',
  'Write about a very bad day with a very good ending.',
  'Write a piece that begins and ends with the same object.',
  'Write about someone who comes home to find everyone already knows their secret.',
  'You wake up with no memory of yesterday. Reconstruct it from the clues around your room.',
  'Write a six-word story, then expand it into a paragraph.',
  'Write about an object in your house that has a secret life at night.',
  'Write about a garden that shrinks a little every night.',
  'Write a scene set entirely inside a lift.',
  'Eavesdropping has become a habit this winter. Write down what you overheard.',
  'Write about a mistake that turned out beautifully.',
  'Write a letter to yourself ten years ago.',
  'Write a letter from yourself ten years in the future.',
  'Describe your morning the way a nature-documentary narrator would.',
  'Write a complaint letter about something absurd.',
  'Write instructions for a task nobody has ever needed to do.',
  'Interview an object in your kitchen.',
  'Write about the last person awake in the whole city.',
  'Write about a shop that sells something impossible.',
  'Describe a place you love without ever naming it.',
  'Write about two strangers stuck somewhere unexpected together.',
  'Write a story where the weather matches the character’s mood a little too exactly.',
  'Invent a myth that explains something small (why cats purr, where dust comes from…).',
  'Write about someone who can suddenly tell when anyone is lying.',
  'Describe what the moon sees on one ordinary night.'
];
